db:
    host: localhost
    port: 3306
    user: db_user     # Insert the name of your database user here
    password: db_pswd # Insert the name of your database password here
    database: db_name # Insert the name of your database here